
def smallspoopyface():
	print('''BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBB8W8BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBM}[QBBBBBBBBBBBBBBB8BB8YX#8BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB8})1p[8BBBBBBBBBBBBBW&M)!1(&BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBB#)1p,:1XWBBBB8BBBBBBW]o;o!1OBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBXI1o,,,op1]OM8888MQ(a::::pi)WBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBB8W)i;,:,,;1[O#BB8XIp:,,:::pi1XBBBBBBBBBBBBBBB
BBBBBB8BBBBBBBB8&M(o,:;(X8BBBBBBBB8#[i;:.;1(MBBBBBBBBBBBBBBB
BBBBB8WBBBBBBBBBBBBW#Y#BBBBMQW8&BBBBBBWQ{XMY&BBBBBBB&8BBBBBB
BBBBB#XBBB&BBBBMBBBBBBBB#88OMBB[OBBBBBBBWBBB&88BBWBMO&BBBBBB
BBBBB#QX8&O8BBY[BBW8BBBYiWBBBBBW[8BBBBB#I&BBBQ#BBOQ#1MBBBBBB
BBBBBM{(WM[MB#!iBM]&BB#i:{B8&BBBBBBBBBXopMBB&IXB8)]OiX8BBBBB
BBBBB8O(##(XB(aaM[IWB8)o.a8[QBBBB8BBB#;,;X8BXiX#)oiiiX&BBBBB
BBBBBBQQ}X(XM!a;}(iXBYp:,,[pOB8&&OBB#p,,,]XB}iQI,:opiO8BBBBB
BBBBBB#M(]IYOaoaap:}BOo:::!;XBOXX!&#p::;:I)&)!Oip)ap1OBBBBBB
BBBBBB8&}IiX]a;))ia]B[::::;,QBi}X:O},::::p1M)i{ap{OiIOBBBBBB
BBBBBBBBOI[&Io:aX(1[BI::::::#M:{Y,!(,o:,:!1#Y1!:o]B[IXBBBBBB
BBBBBBBB#([B1ao.{M[Q&!;::::oW(,[M;oi:11,,a1#Bp,:a[BM(WBBBBBB
BBBBBBBB8O[8}!poo&#X8i,:;p:;{o:I8!;;oI#p,,:QBa!(1}B&QBBBBBBB
BBBBBBBBBWOM&(I1;[B&B1 ,;];o!;;!8!:,a(B#o .}BI!8XQBB8BBBBBBB
BBBBBBBBBB&#B&O(II8BB] o;#p:;o:i8I,:iXBBXppXBQI8B&BBBBBBBBBB
BBBBBBBBBBBBBBBY}]WBBW;ip&].::p)BY.p}8BBB#Q8B&O8BBBBBBBBBBBB
BBBBBBBBBBBBBBBBBMWBBBY()&Wi::)YBBO{8BBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBWQ8B&[]MBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBB8BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB''')


smallspoopyface()